# Is Numpy faster than usual python lists

In [39]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10):my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 81.9 ms
Wall time: 1.53 s


In [40]:
import numpy as np
# Generate some random data
data = np.random.randn(2,3)
data

array([[ 1.77022319, -1.29344623, -0.59209891],
       [-1.11154264, -0.64177634, -1.27198699]])

In [41]:
data * 10

array([[ 17.70223191, -12.9344623 ,  -5.92098914],
       [-11.11542637,  -6.41776337, -12.71986995]])

In [42]:
data + data

array([[ 3.54044638, -2.58689246, -1.18419783],
       [-2.22308527, -1.28355267, -2.54397399]])

In [43]:
data.shape

(2, 3)

In [44]:
data.dtype

dtype('float64')

# Creating ndarrays

In [45]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [46]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
arr2.ndim

2

In [50]:
arr2.shape

(2, 4)

In [52]:
arr1.dtype

dtype('float64')

In [53]:
arr2.dtype

dtype('int32')

# Other ways of Creating numpy arrays

In [54]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [56]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.empty((2,3,2))

array([[[9.05883297e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 8.38290251e+169]],

       [[1.71603894e+185, 3.26879402e-032],
        [2.31908683e-052, 4.54701413e+174],
        [6.10249719e+170, 2.77387219e+180]]])

In [58]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# DataTypes for numpy arrays

In [61]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [63]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

float_arr = arr.astype(np.float64) # covert int datatype to float using astype
print(float_arr.dtype)

int32
float64


In [64]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [65]:
# if we convert the datatype of arr array some value is truncated 
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [66]:
numeric_strings = np.array(['1.25','9.6','4.2'],dtype = np.string_)
numeric_strings.astype(float)

array([1.25, 9.6 , 4.2 ])

In [67]:
init_array = np.arange(10)
print(init_array)
calibers = np.array([.22,.270,.350,.380,.44,.50],dtype = np.float64)
init_array.astype(calibers.dtype)

[0 1 2 3 4 5 6 7 8 9]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [69]:
empty_uint32 = np.empty(8,dtype='u4')
empty_uint32

array([         0,          0, 1889466496,          0,          2,
                0, 4294967295, 4294967295], dtype=uint32)

# Arithmetic Operations Indexing and Slicing

In [70]:
arr = np.array(([1.,2.,3.],[4.,5.,6.]))
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [71]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [72]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [73]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [74]:
# square root of a number
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [76]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [77]:
# comparsion of arrays 
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [78]:
# Basic Indexing and slicing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr[5]

5

In [80]:
arr[5:8]

array([5, 6, 7])

In [81]:
# slicing in numpy is view not copies.below is the examples
arr[5:8] = 12 

In [82]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [88]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [89]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [90]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [83]:
# slicing in python lists are not view is the copies .Below is the example
l = [1,2,3,4,5,6]
l_slice = l[2:4]
l_slice

[3, 4]

In [84]:
l_slice[0]= 10

In [85]:
l_slice

[10, 4]

In [86]:
l

[1, 2, 3, 4, 5, 6]

In [91]:
arr_slice[:]= 64
arr_slice

array([64, 64, 64])

In [93]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [94]:
arr2d[0][2]

3

In [95]:
arr2d[0,2]

3

# Handling Multidimensional array using numpy

In [96]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [97]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [100]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [105]:
arr3d[0] = old_values

In [106]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [107]:
arr3d[1,0]

array([7, 8, 9])

# Boolean and Fancy Indexing

In [108]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [109]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [110]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [113]:
arr2d[1,:2]

array([4, 5])

In [114]:
arr2d[:2,2]

array([3, 6])

In [115]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [116]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [117]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [123]:
arr2d[1:2,:2]

array([[4, 5]])

In [124]:
names = np.array(['Bob','joe','will','Bob','will','joe','joe'])
names

array(['Bob', 'joe', 'will', 'Bob', 'will', 'joe', 'joe'], dtype='<U4')

In [125]:
data = np.random.randn(7,4)
data

array([[ 1.11708743,  1.14324769, -0.26887973,  1.60583212],
       [-0.23745413, -0.53707154,  1.37499246, -0.54004461],
       [-2.07332078,  0.28512001, -1.17829434,  1.30656637],
       [-0.17159157, -0.92921973,  0.27391809, -0.53346996],
       [ 0.48905318, -0.20967091,  0.3793722 , -2.15964942],
       [-0.69013594, -0.58516348, -2.45002238, -1.23239817],
       [ 0.54038543, -0.99948264, -1.00733479, -0.21665135]])

In [126]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [127]:
data[names == 'Bob']

array([[ 1.11708743,  1.14324769, -0.26887973,  1.60583212],
       [-0.17159157, -0.92921973,  0.27391809, -0.53346996]])

In [128]:
data[names == 'Bob',2:]

array([[-0.26887973,  1.60583212],
       [ 0.27391809, -0.53346996]])

In [129]:
data[names == 'Bob',3]

array([ 1.60583212, -0.53346996])

In [130]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [131]:
data[~(names == 'Bob')]

array([[-0.23745413, -0.53707154,  1.37499246, -0.54004461],
       [-2.07332078,  0.28512001, -1.17829434,  1.30656637],
       [ 0.48905318, -0.20967091,  0.3793722 , -2.15964942],
       [-0.69013594, -0.58516348, -2.45002238, -1.23239817],
       [ 0.54038543, -0.99948264, -1.00733479, -0.21665135]])

In [132]:
cond = names == 'Bob'
data[~cond]

array([[-0.23745413, -0.53707154,  1.37499246, -0.54004461],
       [-2.07332078,  0.28512001, -1.17829434,  1.30656637],
       [ 0.48905318, -0.20967091,  0.3793722 , -2.15964942],
       [-0.69013594, -0.58516348, -2.45002238, -1.23239817],
       [ 0.54038543, -0.99948264, -1.00733479, -0.21665135]])

In [134]:
mask = (names == 'Bob')|(names == 'will')
mask

array([ True, False,  True,  True,  True, False, False])

In [135]:
data[mask]

array([[ 1.11708743,  1.14324769, -0.26887973,  1.60583212],
       [-2.07332078,  0.28512001, -1.17829434,  1.30656637],
       [-0.17159157, -0.92921973,  0.27391809, -0.53346996],
       [ 0.48905318, -0.20967091,  0.3793722 , -2.15964942]])

In [136]:
# noise removal or clean up data
data[data < 0] = 0
data

array([[1.11708743, 1.14324769, 0.        , 1.60583212],
       [0.        , 0.        , 1.37499246, 0.        ],
       [0.        , 0.28512001, 0.        , 1.30656637],
       [0.        , 0.        , 0.27391809, 0.        ],
       [0.48905318, 0.        , 0.3793722 , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.54038543, 0.        , 0.        , 0.        ]])

In [137]:
data[names != 'joe']  = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.37499246, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.54038543, 0.        , 0.        , 0.        ]])

#  Fancy Indexing

In [138]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [139]:
# Fancy indexing
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [140]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [141]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [142]:
# 2d fancy indexing
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [146]:
# re-order column using fancy indexing
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Basic ndarrays Operations

In [147]:
# Transposing arrays
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [148]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [149]:
# dot function for multiplication
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

# Transposing and Swap array axes

In [154]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [155]:
arr.transpose((1 , 0 , 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [156]:
#swap axes using swapaxes function
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# Universal Functions in numpy

In [157]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [158]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [159]:
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [160]:
x = np.random.randn(5)
y = np.random.randn(5)

In [161]:
x

array([-0.0432625 , -0.36469606,  0.18310916, -0.35998646,  1.1507365 ])

In [162]:
y

array([-1.29727465,  0.97485951,  0.45938559, -0.6380372 , -0.90663229])

In [163]:
np.maximum(x,y)

array([-0.0432625 ,  0.97485951,  0.45938559, -0.35998646,  1.1507365 ])

In [164]:
# splits function using modf function
arr = np.random.randn(5)*5
arr

array([ -4.07109347, -10.96552722,   4.04083656,  -0.369311  ,
         2.9588631 ])

In [166]:
remainder,whole_part = np.modf(arr)

In [167]:
remainder

array([-0.07109347, -0.96552722,  0.04083656, -0.369311  ,  0.9588631 ])

In [168]:
whole_part

array([ -4., -10.,   4.,  -0.,   2.])

# File IO using numpy

In [178]:
arr =  np.arange(10)
np.save('outfile',arr)

In [180]:
b = np.load('outfile.npy')
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
#  it helps to store multiple arrays
np.savez('outfile.npz',a=arr,b=arr)

In [182]:
# this file return dictionary that why we use arch
arch = np.load('outfile.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
#compressed file 
np.savez_compressed('outfile.npz',a=arr,b=arr)

# Linear Algebra using numpy

In [185]:
x = np.array(([[1.,2.,3.],[4.,5.,6.]]))
y = np.array(([6.,23.],[-1,7],[8,9]))

In [186]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [187]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [188]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [189]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [190]:
np.dot(x , np.ones(3))

array([ 6., 15.])

In [191]:
x @ np.ones(3)

array([ 6., 15.])

In [192]:
from numpy.linalg import inv , qr
x = np.random.randn(3,3)
mat = x.T.dot(x) # laplasian

In [193]:
inv(mat)

array([[ 0.58654986,  0.2222269 , -0.04360802],
       [ 0.2222269 ,  0.99821416, -0.52155634],
       [-0.04360802, -0.52155634,  0.81051516]])

In [194]:
mat.dot(inv(mat)) # Identity matrix

array([[ 1.00000000e+00,  9.91625770e-18, -3.69652735e-17],
       [-9.97712302e-17,  1.00000000e+00,  1.29950167e-16],
       [-1.17667559e-17,  9.83427990e-17,  1.00000000e+00]])

In [195]:
q , r = qr(mat) # matrix decomposition

In [196]:
r

array([[-1.99263595,  1.12937268,  0.77776793],
       [ 0.        , -1.70977462, -1.75052825],
       [ 0.        ,  0.        ,  1.03647397]])

# Broadcasting Rule in numpy

In [198]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [199]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [200]:
# Deleting mean from row
arr = np.random.randn(4,3)
arr.mean(0)

array([ 0.06439487,  1.17600898, -0.34206162])

In [202]:
demeaned = arr - arr.mean(0)
demeaned

array([[-0.13643018, -0.41844519, -0.89674284],
       [ 0.42894809,  0.18570845, -0.02484281],
       [ 0.57549731,  0.4788433 , -0.5692019 ],
       [-0.86801521, -0.24610656,  1.49078755]])

In [203]:
demeaned.mean(0)

array([-2.77555756e-17, -5.55111512e-17,  0.00000000e+00])

In [204]:
# deleting mean from column
arr
row_means = arr.mean(1)
row_means.shape

(4,)

In [205]:
row_means.reshape(4,1)

array([[-0.18442533],
       [ 0.49605198],
       [ 0.46116031],
       [ 0.42500267]])

In [206]:
demeaned = arr - row_means.reshape(4,1)

In [207]:
demeaned.mean(1)

array([ 0.00000000e+00, -3.70074342e-17, -7.40148683e-17, -7.40148683e-17])

# Sorting and Set Operations in numpy

In [208]:
arr = np.random.randn(4)
arr

array([-1.56018248, -2.12738549, -0.75261027, -1.71997482])

In [209]:
arr.sort()

In [210]:
arr

array([-2.12738549, -1.71997482, -1.56018248, -0.75261027])

In [211]:
arr = np.random.randn(4,3)
arr

array([[ 0.79963167,  0.17439634,  0.28652031],
       [-0.68813322, -0.89440377,  0.24176369],
       [ 0.90902194,  0.03819719, -1.44361386],
       [ 1.15521539,  0.65122827,  2.98040621]])

In [212]:
arr.sort(1) # row wise sort 

In [213]:
arr

array([[ 0.17439634,  0.28652031,  0.79963167],
       [-0.89440377, -0.68813322,  0.24176369],
       [-1.44361386,  0.03819719,  0.90902194],
       [ 0.65122827,  1.15521539,  2.98040621]])

In [214]:
arr.sort(0) # column wise sort
arr

array([[-1.44361386, -0.68813322,  0.24176369],
       [-0.89440377,  0.03819719,  0.79963167],
       [ 0.17439634,  0.28652031,  0.90902194],
       [ 0.65122827,  1.15521539,  2.98040621]])

In [215]:
large_arr = np.random.randn(1000)
large_arr.sort()
# 5% Quantile
large_arr[int(0.05 * len(large_arr))]

-1.7565077311682495

In [216]:
names = np.array(['Bob' ,'Joe' ,'Will','Bob','Will','Joe','Joe'])
np.unique(names) # first sort then return unique

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [217]:
ints = np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [218]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [219]:
values = np.array([6,0,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False,  True,  True, False,  True])